apiVersion: v1
kind: Service
metadata:
  name: spring-app-service
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: spring-app
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.app.service.nodePort }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-app
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: spring-app
  template:
    metadata:
      labels:
        app: spring-app
    spec:
      securityContext:
        {{- toYaml .Values.app.securityContext | nindent 8 }}
      # Init Container: Wait for MySQL and Kafka to be ready
      initContainers:
      - name: wait-for-services
        image: busybox:1.28
        command: ['sh', '-c', "until nc -z mysql-service 3306 && nc -z kafka-service 9092; do echo waiting for mysql and kafka; sleep 3; done; echo services are ready"]
      
      containers:
      - name: app
        image: {{ .Values.app.image }}
        imagePullPolicy: Never
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: "mysql-service"
        - name: DB_NAME
          value: "devopsdb"
        - name: DB_USER
          value: "root"
        - name: DB_PASS
          value: "password"
        - name: KAFKA_BROKER
          value: "kafka-service:9092"
        - name: SPRING_KAFKA_ADMIN_FAIL_FAST
          value: {{ .Values.app.env.SPRING_KAFKA_ADMIN_FAIL_FAST | quote }}
        - name: SPRING_KAFKA_LISTENER_MISSING_TOPICS_FATAL
          value: {{ .Values.app.env.SPRING_KAFKA_LISTENER_MISSING_TOPICS_FATAL | quote }}
        - name: SPRING_KAFKA_CONSUMER_PROPERTIES_RECONNECT_BACKOFF_MS
          value: {{ .Values.app.env.SPRING_KAFKA_CONSUMER_PROPERTIES_RECONNECT_BACKOFF_MS | quote }}
        - name: SPRING_KAFKA_CONSUMER_PROPERTIES_RECONNECT_BACKOFF_MAX_MS
          value: {{ .Values.app.env.SPRING_KAFKA_CONSUMER_PROPERTIES_RECONNECT_BACKOFF_MAX_MS | quote }}
        resources:
          {{- toYaml .Values.app.resources | nindent 10 }}
        # Reliability checks
        startupProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 60
          periodSeconds: 3
        livenessProbe:
          tcpSocket:
            port: 8080
          initialDelaySeconds: 45
          periodSeconds: 15
        readinessProbe:
          httpGet:
            path: {{ .Values.app.readinessProbe.httpGet.path }}
            port: {{ .Values.app.readinessProbe.httpGet.port }}
          initialDelaySeconds: 45
          periodSeconds: 10
          failureThreshold: 10
