apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - name: broker
      port: 9092
    - name: controller
      port: 29093
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
      - name: kafka
        image: {{ .Values.kafka.image }}
        env:
        - name: KAFKA_NODE_ID
          value: "1"
        - name: KAFKA_PROCESS_ROLES
          value: "broker,controller"
        - name: KAFKA_CONTROLLER_QUORUM_VOTERS
          value: "1@localhost:29093"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT"
        - name: KAFKA_LISTENERS
          value: "INTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:29093"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTERNAL://kafka-service:9092"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: "INTERNAL"
        - name: KAFKA_CONTROLLER_LISTENER_NAMES
          value: "CONTROLLER"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: CLUSTER_ID
          value: {{ .Values.kafka.clusterId }}
        - name: LOG_DIR
          value: "/tmp/kafka-logs"
        resources:
          {{- toYaml .Values.kafka.resources | nindent 10 }}
        # TCP Socket probes: Fast, efficient, and reliable for Kafka
        livenessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 60
          periodSeconds: 15
          failureThreshold: 5
        readinessProbe:
          tcpSocket:
            port: 9092
          initialDelaySeconds: 60
          periodSeconds: 15
          failureThreshold: 5
